version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/overseer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/host"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:45"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
